### ISSUE TITLE
Link to youtube video down?

### ISSUE THREAD

**Issue by EMCP** [stefanRitter/emptyApp#1]
Hi Stefan, 

  First off thank you for building this seed app.  My friend is loving it since I showed him your google interview video.  Did Google take that video off youtube?  I am unable to find it.

Perhaps putting it in the README.md would be useful for those who stumble upon this project?

**Comment by stefanRitter** [comment]
Thanks for this! I'll do just that, here is the link: https://www.youtube.com/watch?v=k_7zdqz01sk
